jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Competitions\AdminBundle\Entity\Admin: sha512
          

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       # in_memory:
       #     memory:
       #         users:
       #             user:  { password: userpass, roles: [ 'ROLE_USER' ] }
       #             admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                   
        main:
          entity: { class: CompetitionsAdminBundle:Admin }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        
        secured_area:
            pattern:    ^/admin
            form_login:
                check_path: login_check
                login_path: login
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
            logout:
                path:   logout
            #    target: _demo
            anonymous: ~
            

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: ROLE_ADMIN }
