Competitions\AdminBundle\Entity\Admin:
    type: entity
    table: null
    repositoryClass: Competitions\AdminBundle\Repository\AdminRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: '128'
        salt:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        active:
            type: string
            length: 255
    lifecycleCallbacks: {  }
