Competitions\AdminBundle\Entity\Competition:
  type: entity
  table: competition
  repositoryClass: Competitions\AdminBundle\Repository\CompetitionRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 128
      
    description: 
      type: string
      length: 512
      
    start_date:
      type: date
      
    end_date:
      type: date
      nullable: true
      
    location:
      type: string
      length: 128
      
    website:
      type: string
      length: 128
      nullable: true
      
    logo:
      type: string
      length: 128
      nullable: true
      
  manyToMany:
    categories:
      targetEntity: Category
      inversedBy: competitions
      joinTable:
        name: competitioncategory
        joinColumns:
          competition_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
    
    
    